# Generated by Django 6.0.3 on 2026-04-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_backfill_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach_name',
        ),
    ]
