# Generated by Django 6.0.3 on 2026-03-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_volleyplayer_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('serve_accuracy', models.IntegerField(help_text='0-100')),
                ('spike_success', models.IntegerField(help_text='0-100')),
                ('block_rate', models.IntegerField(help_text='0-100')),
                ('dig_success', models.IntegerField(help_text='0-100')),
                ('set_accuracy', models.IntegerField(help_text='0-100')),
                ('receive_rating', models.IntegerField(help_text='0-100')),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.volleyplayer')),
            ],
            options={
                'verbose_name_plural': 'player stats',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
