# Generated by Django 6.0.3 on 2026-03-22 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_volleyplayer_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(choices=[('Sprain', 'Sprain'), ('Strain', 'Strain'), ('Fracture', 'Fracture'), ('Concussion', 'Concussion'), ('Dislocation', 'Dislocation'), ('Tendinitis', 'Tendinitis'), ('Bruise', 'Bruise'), ('Other', 'Other')], max_length=50)),
                ('body_part', models.CharField(choices=[('Knee', 'Knee'), ('Ankle', 'Ankle'), ('Shoulder', 'Shoulder'), ('Wrist', 'Wrist'), ('Back', 'Back'), ('Hip', 'Hip'), ('Finger', 'Finger'), ('Elbow', 'Elbow'), ('Head', 'Head'), ('Other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('date_reported', models.DateField()),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Recovering', 'Recovering'), ('Cleared', 'Cleared')], default='Active', max_length=20)),
                ('medical_notes', models.TextField(blank=True)),
                ('reported_by', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='players.volleyplayer')),
            ],
            options={
                'verbose_name_plural': 'injuries',
                'ordering': ['-date_reported'],
            },
        ),
    ]
