# Generated by Django 6.0.3 on 2026-04-26 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injuries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='reported_by_user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who reported this injury (preferred over the legacy text field).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_injuries', to=settings.AUTH_USER_MODEL),
        ),
    ]
