# Generated by Django 6.0.3 on 2026-04-26 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_volleyplayer_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('manager', 'Manager'), ('scout', 'Scout'), ('admin', 'Admin')], default='player', max_length=16)),
                ('linked_player', models.ForeignKey(blank=True, help_text='When role=player, the VolleyPlayer record this account represents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='players.volleyplayer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_e16858_idx')],
            },
        ),
    ]
