# Generated by Django 6.0.3 on 2026-04-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_volleyplayer_photo'),
        ('teams', '0004_remove_team_coach_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('SETTER', 'Setter'), ('OH1', 'Outside Hitter 1'), ('OH2', 'Outside Hitter 2'), ('MB1', 'Middle Blocker 1'), ('MB2', 'Middle Blocker 2'), ('OPP', 'Opposite'), ('LIBERO', 'Libero')], max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_slots', to='teams.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_slots', to='players.volleyplayer')),
            ],
            options={
                'unique_together': {('event', 'player'), ('event', 'position')},
            },
        ),
    ]
