# Generated by Django 6.0.3 on 2026-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_volleyplayer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='volleyplayer',
            name='photo',
            field=models.CharField(blank=True, default='', help_text="Relative path under static/, e.g. 'players/portraits/p1.jpg'", max_length=200),
        ),
    ]
