# Generated by Django 6.0.3 on 2026-04-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('players', '0003_volleyplayer_photo'),
        ('teams', '0004_remove_team_coach_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not Attending'), ('maybe', 'Maybe')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='teams.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='players.volleyplayer')),
            ],
            options={
                'unique_together': {('event', 'player')},
            },
        ),
    ]
